import { Question } from "./types";

export const relationshipQuestions: Question[] = [
  // --- Gottman: Four Horsemen ---
  {
    id: "a1",
    framework: "gottman_horsemen",
    dimension: "criticism",
    format: "scenario",
    text: "Your partner forgot to do something they promised. What's your gut reaction?",
    options: [
      {
        id: "a1a",
        text: "\"You always forget things. You just don't care enough.\"",
        score: 4,
      },
      {
        id: "a1b",
        text: "\"Hey, the thing didn't get done — can we figure out a plan?\"",
        score: 1,
      },
      {
        id: "a1c",
        text: "\"I'm frustrated because this keeps happening and it makes me feel unimportant.\"",
        score: 2,
      },
      {
        id: "a1d",
        text: "Say nothing but feel resentful inside.",
        score: 3,
      },
    ],
    sourceInstrument: "Four Horsemen Questionnaire, adapted",
    modes: ["relationship"],
  },
  {
    id: "a2",
    framework: "gottman_horsemen",
    dimension: "contempt",
    format: "likert",
    text: "When we argue, I sometimes feel like I'm just better at handling emotions than my partner.",
    likertLabels: { low: "Never", high: "Very often" },
    sourceInstrument: "Four Horsemen Questionnaire, adapted",
    modes: ["relationship"],
  },
  {
    id: "a3",
    framework: "gottman_horsemen",
    dimension: "defensiveness",
    format: "scenario",
    text: "Your partner says \"You haven't been very present lately.\" Your first instinct is to:",
    options: [
      {
        id: "a3a",
        text: "\"That's not fair — I've been really busy with work.\"",
        score: 4,
      },
      {
        id: "a3b",
        text: "\"You're right, I have been distracted. Tell me more about how it's affecting you.\"",
        score: 1,
      },
      {
        id: "a3c",
        text: "\"Well, you haven't exactly been a ray of sunshine either.\"",
        score: 5,
      },
      {
        id: "a3d",
        text: "\"I hear you. Let me think about that for a second.\"",
        score: 2,
      },
    ],
    sourceInstrument: "Four Horsemen Questionnaire, adapted",
    modes: ["relationship"],
  },
  {
    id: "a4",
    framework: "gottman_horsemen",
    dimension: "stonewalling",
    format: "forced_choice",
    text: "During a heated disagreement, which describes you better?",
    forcedChoices: [
      {
        id: "a4a",
        text: "I tend to shut down and go quiet until the storm passes.",
        score: 4,
      },
      {
        id: "a4b",
        text: "I stay engaged even when it's uncomfortable, sometimes too much.",
        score: 1,
      },
    ],
    sourceInstrument: "Four Horsemen Questionnaire, adapted",
    modes: ["relationship"],
  },
  // --- Gottman: Sound Relationship House ---
  {
    id: "a5",
    framework: "gottman_srh",
    dimension: "love_maps",
    format: "likert",
    text: "I know my partner's biggest current worry or stress.",
    likertLabels: { low: "Not at all", high: "Absolutely" },
    sourceInstrument: "Sound Relationship House scales, adapted",
    modes: ["relationship"],
  },
  {
    id: "a6",
    framework: "gottman_srh",
    dimension: "fondness",
    format: "likert",
    text: "I can easily list three things I genuinely admire about my partner.",
    likertLabels: { low: "Strongly disagree", high: "Strongly agree" },
    sourceInstrument: "Sound Relationship House scales, adapted",
    modes: ["relationship"],
  },
  {
    id: "a7",
    framework: "gottman_srh",
    dimension: "turning_toward",
    format: "scenario",
    text: "Your partner excitedly tells you about something that happened at work. You're in the middle of something. What do you do?",
    options: [
      {
        id: "a7a",
        text: "Put down what I'm doing and give them my full attention.",
        score: 1,
      },
      {
        id: "a7b",
        text: "Half-listen while finishing my task, nodding along.",
        score: 3,
      },
      {
        id: "a7c",
        text: "\"Can you tell me later? I'm in the middle of something.\"",
        score: 4,
      },
      {
        id: "a7d",
        text: "Acknowledge it briefly: \"Oh cool!\" and move on.",
        score: 2,
      },
    ],
    sourceInstrument: "Sound Relationship House scales, adapted",
    modes: ["relationship"],
  },
  // --- Attachment ---
  {
    id: "a8",
    framework: "attachment",
    dimension: "anxiety",
    format: "likert",
    text: "I often worry that my partner doesn't love me as much as I love them.",
    likertLabels: { low: "Strongly disagree", high: "Strongly agree" },
    sourceInstrument: "ECR-R, adapted",
    modes: ["relationship"],
  },
  {
    id: "a9",
    framework: "attachment",
    dimension: "avoidance",
    format: "likert",
    text: "I find it difficult to fully depend on my partner.",
    likertLabels: { low: "Strongly disagree", high: "Strongly agree" },
    sourceInstrument: "ECR-R, adapted",
    modes: ["relationship"],
  },
  {
    id: "a10",
    framework: "attachment",
    dimension: "anxiety",
    format: "forced_choice",
    text: "Which resonates more with you?",
    forcedChoices: [
      {
        id: "a10a",
        text: "I need a lot of reassurance that things are okay between us.",
        score: 5,
      },
      {
        id: "a10b",
        text: "I generally trust that things are fine unless told otherwise.",
        score: 2,
      },
    ],
    sourceInstrument: "ECR-R, adapted",
    modes: ["relationship"],
  },
  // --- Big Five ---
  {
    id: "a11",
    framework: "big_five",
    dimension: "neuroticism",
    format: "likert",
    text: "Small disagreements can spiral in my head into worst-case scenarios about the relationship.",
    likertLabels: { low: "Never", high: "Very often" },
    sourceInstrument: "BFI-K, adapted",
    modes: ["relationship"],
  },
  {
    id: "a12",
    framework: "big_five",
    dimension: "conscientiousness",
    format: "likert",
    text: "I follow through on plans and commitments in my relationship.",
    likertLabels: { low: "Rarely", high: "Always" },
    sourceInstrument: "BFI-K, adapted",
    modes: ["relationship"],
  },
  {
    id: "a13",
    framework: "big_five",
    dimension: "agreeableness",
    format: "forced_choice",
    text: "In a disagreement, which sounds more like you?",
    forcedChoices: [
      {
        id: "a13a",
        text: "I'd rather compromise quickly and restore harmony.",
        score: 5,
      },
      {
        id: "a13b",
        text: "I need to fully hash things out, even if it takes a while.",
        score: 2,
      },
    ],
    sourceInstrument: "BFI-K, adapted",
    modes: ["relationship"],
  },
  // --- CSI (relationship mode only) ---
  {
    id: "a14",
    framework: "csi",
    dimension: "satisfaction",
    format: "likert",
    text: "Overall, how satisfied are you with your relationship?",
    likertLabels: { low: "Not at all", high: "Completely" },
    sourceInstrument: "CSI-4",
    modes: ["relationship"],
  },
  {
    id: "a15",
    framework: "csi",
    dimension: "satisfaction",
    format: "likert",
    text: "How often do you wish you hadn't gotten into this relationship?",
    likertLabels: { low: "Very often", high: "Never" },
    sourceInstrument: "CSI-4",
    modes: ["relationship"],
  },
  // --- Love Languages ---
  {
    id: "a16",
    framework: "love_languages",
    dimension: "quality_time",
    format: "forced_choice",
    text: "Which makes you feel more loved?",
    forcedChoices: [
      {
        id: "a16a",
        text: "My partner puts their phone away and gives me their undivided attention.",
        score: 5,
      },
      {
        id: "a16b",
        text: "My partner surprises me with a thoughtful compliment.",
        score: 5,
      },
    ],
    sourceInstrument: "Love Languages assessment, adapted",
    modes: ["relationship"],
  },
  {
    id: "a17",
    framework: "love_languages",
    dimension: "acts_of_service",
    format: "forced_choice",
    text: "Which would mean more to you?",
    forcedChoices: [
      {
        id: "a17a",
        text: "My partner takes care of a chore I've been putting off.",
        score: 5,
      },
      {
        id: "a17b",
        text: "My partner gives me a long, warm hug after a hard day.",
        score: 5,
      },
    ],
    sourceInstrument: "Love Languages assessment, adapted",
    modes: ["relationship"],
  },
  {
    id: "a18",
    framework: "love_languages",
    dimension: "gifts",
    format: "forced_choice",
    text: "Which gesture would touch you more?",
    forcedChoices: [
      {
        id: "a18a",
        text: "Receiving a small, thoughtful gift that shows they were thinking of me.",
        score: 5,
      },
      {
        id: "a18b",
        text: "Hearing \"I'm really proud of you\" at just the right moment.",
        score: 5,
      },
    ],
    sourceInstrument: "Love Languages assessment, adapted",
    modes: ["relationship"],
  },
];

export const singleQuestions: Question[] = [
  // --- Gottman (pattern-based) ---
  {
    id: "b1",
    framework: "gottman_horsemen",
    dimension: "criticism",
    format: "scenario",
    text: "Think about past relationships. When you were upset with a partner, you were most likely to:",
    options: [
      {
        id: "b1a",
        text: "Point out what they were doing wrong as a pattern: \"You always...\"",
        score: 4,
      },
      {
        id: "b1b",
        text: "Describe the specific thing that bothered you without generalizing.",
        score: 1,
      },
      {
        id: "b1c",
        text: "Bottle it up until you couldn't anymore, then it all came out at once.",
        score: 3,
      },
      {
        id: "b1d",
        text: "Try to address it calmly, but end up getting emotional.",
        score: 2,
      },
    ],
    sourceInstrument: "Four Horsemen Questionnaire, adapted for singles",
    modes: ["single"],
  },
  {
    id: "b2",
    framework: "gottman_horsemen",
    dimension: "stonewalling",
    format: "likert",
    text: "In past relationships, when things got heated, I would shut down and stop responding.",
    likertLabels: { low: "Never", high: "Very often" },
    sourceInstrument: "Four Horsemen Questionnaire, adapted for singles",
    modes: ["single"],
  },
  {
    id: "b3",
    framework: "gottman_horsemen",
    dimension: "defensiveness",
    format: "forced_choice",
    text: "When an ex gave you feedback, which was more typical?",
    forcedChoices: [
      {
        id: "b3a",
        text: "I'd listen, but internally I was building my defense.",
        score: 4,
      },
      {
        id: "b3b",
        text: "I'd try to understand their perspective, even if it stung.",
        score: 1,
      },
    ],
    sourceInstrument: "Four Horsemen Questionnaire, adapted for singles",
    modes: ["single"],
  },
  {
    id: "b4",
    framework: "gottman_horsemen",
    dimension: "contempt",
    format: "scenario",
    text: "Be honest: in past arguments, how often did you think something like \"I can't believe I'm with someone who...\"?",
    options: [
      { id: "b4a", text: "Rarely, if ever.", score: 1 },
      { id: "b4b", text: "In the heat of the moment, sure.", score: 3 },
      { id: "b4c", text: "More than I'd like to admit.", score: 4 },
      {
        id: "b4d",
        text: "That kind of thinking contributed to breakups.",
        score: 5,
      },
    ],
    sourceInstrument: "Four Horsemen Questionnaire, adapted for singles",
    modes: ["single"],
  },
  // --- Attachment ---
  {
    id: "b5",
    framework: "attachment",
    dimension: "anxiety",
    format: "likert",
    text: "I tend to worry that people I care about will leave.",
    likertLabels: { low: "Strongly disagree", high: "Strongly agree" },
    sourceInstrument: "ECR-R, adapted",
    modes: ["single"],
  },
  {
    id: "b6",
    framework: "attachment",
    dimension: "avoidance",
    format: "likert",
    text: "I prefer not to show a partner how I feel deep down.",
    likertLabels: { low: "Strongly disagree", high: "Strongly agree" },
    sourceInstrument: "ECR-R, adapted",
    modes: ["single"],
  },
  {
    id: "b7",
    framework: "attachment",
    dimension: "avoidance",
    format: "forced_choice",
    text: "Which resonates more?",
    forcedChoices: [
      {
        id: "b7a",
        text: "I value my independence in relationships — sometimes too much.",
        score: 5,
      },
      {
        id: "b7b",
        text: "I crave closeness and sometimes come on too strong.",
        score: 1,
      },
    ],
    sourceInstrument: "ECR-R, adapted",
    modes: ["single"],
  },
  // --- Big Five ---
  {
    id: "b8",
    framework: "big_five",
    dimension: "neuroticism",
    format: "likert",
    text: "I tend to replay conversations in my head, imagining all the ways things could go wrong.",
    likertLabels: { low: "Never", high: "Constantly" },
    sourceInstrument: "BFI-K, adapted",
    modes: ["single"],
  },
  {
    id: "b9",
    framework: "big_five",
    dimension: "conscientiousness",
    format: "likert",
    text: "People would describe me as reliable and organized.",
    likertLabels: { low: "Strongly disagree", high: "Strongly agree" },
    sourceInstrument: "BFI-K, adapted",
    modes: ["single"],
  },
  {
    id: "b10",
    framework: "big_five",
    dimension: "agreeableness",
    format: "scenario",
    text: "A friend criticizes a decision you made. Your response is usually to:",
    options: [
      {
        id: "b10a",
        text: "Thank them for the honesty and reflect on it.",
        score: 5,
      },
      {
        id: "b10b",
        text: "Feel hurt and pull away for a bit.",
        score: 2,
      },
      {
        id: "b10c",
        text: "Push back — you made that decision for good reasons.",
        score: 1,
      },
      {
        id: "b10d",
        text: "Agree to keep the peace, even if you don't really agree.",
        score: 4,
      },
    ],
    sourceInstrument: "BFI-K, adapted",
    modes: ["single"],
  },
  // --- Love Languages ---
  {
    id: "b11",
    framework: "love_languages",
    dimension: "quality_time",
    format: "forced_choice",
    text: "Which matters more to you in a relationship?",
    forcedChoices: [
      {
        id: "b11a",
        text: "Long, uninterrupted conversations where we really connect.",
        score: 5,
      },
      {
        id: "b11b",
        text: "Small, everyday acts that show they're thinking of me.",
        score: 5,
      },
    ],
    sourceInstrument: "Love Languages assessment, adapted",
    modes: ["single"],
  },
  {
    id: "b12",
    framework: "love_languages",
    dimension: "physical_touch",
    format: "forced_choice",
    text: "Which would you miss more if it disappeared from a relationship?",
    forcedChoices: [
      {
        id: "b12a",
        text: "Physical affection — hand-holding, hugs, closeness.",
        score: 5,
      },
      {
        id: "b12b",
        text: "Hearing \"I love you\" and other verbal affirmations.",
        score: 5,
      },
    ],
    sourceInstrument: "Love Languages assessment, adapted",
    modes: ["single"],
  },
];
